# Generated by Django 4.1.3 on 2022-12-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
