# Generated by Django 4.1.3 on 2022-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_choice_is_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(max_length=64, null=True),
        ),
    ]
